return {
    --{
    --    "windwp/nvim-autopairs",
    --    event = "InsertEnter",
    --    opts = {
    --        disable_filetype = { "TelescopePrompt" },
    --    },
    --},
    --{
    --    "norcalli/nvim-colorizer.lua",
    --    event = { "BufReadPre", "BufNewFile" },
    --    --config = true,
    --    opts = { '*', { lowercase = true, }, },
    --    --config = function()
    --    --    require 'colorizer'.setup({ lowercase = true, })
    --    --end
    --},
    --{
    --    "stevearc/conform.nvim",
    --    --event = { "BufReadPre", "BufNewFile" },
    --    keys = {
    --        "<leader>f",
    --        function()
    --            require 'conform'.format({
    --                lsp_fallback = true,
    --                async = true,
    --                timeout_ms = 500,
    --            })
    --        end,
    --        { "n", "v" },
    --        desc = "Format file or range (in visual mode)",
    --    },
    --    opts = {
    --        formatters_by_ft = {
    --            lua = { "stylua" },
    --            svelte = { { "prettierd", "prettier" } },
    --            javascript = { { "prettierd", "prettier" } },
    --            typescript = { { "prettierd", "prettier" } },
    --            javascriptreact = { { "prettierd", "prettier" } },
    --            typescriptreact = { { "prettierd", "prettier" } },
    --            json = { { "prettierd", "prettier" } },
    --            graphql = { { "prettierd", "prettier" } },
    --            java = { "google-java-format" },
    --            kotlin = { "ktlint" },
    --            ruby = { "standardrb" },
    --            markdown = { { "prettierd", "prettier" } },
    --            erb = { "htmlbeautifier" },
    --            html = { "htmlbeautifier" },
    --            bash = { "beautysh" },
    --            proto = { "buf" },
    --            rust = { "rustfmt" },
    --            yaml = { "yamlfix" },
    --            toml = { "taplo" },
    --            css = { { "prettierd", "prettier" } },
    --            scss = { { "prettierd", "prettier" } },
    --        },
    --    },
    --}
}
